### PR TITLE
#61 Add ESLint to CI/CD Pipeline

### PR DESCRIPTION
**Pull request by danwyl**
### Adding ESLint to the CI/CD Pipeline

We now will run ESLint on all files in `src/` and require it to pass.

I've stored the config for eslint in `.config/eslint-config.mjs`, which we can call with the `--config` flag in the github action.

### CODE REVIEW

**Comment by danwyl** [comment]
The ESLint test is going to fail and it's not the fault of my code, we just have ESLint errors already in `dev`.

**Review by ravishende — APPROVED** [review]
Looks good!

**Comment by danwyl** [comment]
I think we should just merge this though and have the linter fail, but maybe this break things? I'm not entirely sure

**Comment by ravishende** [comment]
We can push it through, but then the next time anyone wants to PR something they'll first have to handle the fails of all the other files in the linter. That said, we can just push it through and then immediately fix the files and PR that

**Comment by danwyl** [comment]
Sounds good. I'll PR then.

**Pull request merged**
