### PR TITLE
Add end-to-end tests

### PR DESCRIPTION
**Pull request by BenjiRyujin**
#65 - Wrote end-to-end tests for navbar, notes page, daily log, calendar, and settings pages.

### CODE REVIEW

**Comment by BenjiRyujin** [comment]
Still waiting on Daniel to finish his tests on the issue since his checkbox isn't checked, but I thought I'd make the PR anyway.

**Comment by BenjiRyujin** [comment]
Settings.html merge conflicts are a result of me adding ID tags to the update and logout buttons, not sure what the other merge conflicts are?

**Comment by shambhavi-20** [comment]
Can you pull from dev and see where the conflicts are?

**Review by shambhavi-20 — APPROVED** [review]
Looks Good! I fixed the merge conflicts. So, this can be merged into dev now.

**Pull request merged**
